version: '3.2'

services:

  app:
    image: photosort
    ports:
     - 8080:8080
    networks:
     - internal
    volumes:
     - /data/archive/photosort/input:/input
     - /data/archive/output:/output
     - /data/archive/photosort/delete:/delete
    environment:
     - 'SECRET_KEY=badSecretKey'
     - 'REDIS_URL=redis://10.0.2.205:6379/0'

networks:
 internal: